function [XDEN,wDEC] = denoise2d(X)
% FUNC_DENOISE_SW2D Saved Denoising Process.
%   X: matrix of data
%   -----------------
%   XDEN: matrix of denoised data
%   wDEC: stationary wavelet decomposition

%  Auto-generated by Wavelet Toolbox on 09-Feb-2015 14:41:41

% Analysis parameters.
%---------------------
wname = 'sym3';
level = 5;

% Denoising parameters.
%-----------------------
% meth = 'penallo';
% scal_OR_alfa = 4;
sorh = 'h';    % Specified soft or hard thresholding
thrSettings =  [...
    47.097366333007812     47.097366333007812     47.097366333007812     47.097366333007812     47.097366333007812 ; ...
    47.097366333007812     47.097366333007812     47.097366333007812     47.097366333007812     47.097366333007812 ; ...
    47.097366333007812     47.097366333007812     47.097366333007812     47.097366333007812     47.097366333007812   ...
    ];
roundFLAG = false;

% Decompose using SWT2.
%---------------------
wDEC = swt2(X,level,wname);

% Denoise.
%---------
permDir = [1 3 2];
for j = 1:level
    for kk=1:3
        ind = (permDir(kk)-1)*level+j;
        thr = thrSettings(kk,j);
        wDEC(:,:,ind) = wthresh(wDEC(:,:,ind),sorh,thr);
    end
end

% Reconstruct the denoise signal using ISWT2.
%-------------------------------------------
XDEN = iswt2(wDEC,wname);
if roundFLAG , XDEN = round(XDEN); end
