function result = menu()

movingBar = struct(...
    'prompt', 'moving bar: 0.1 Hz (300 s)', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.MovingBar), ...
    'constants', ...
    struct(...
    'stimulus', 'moving bar', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 50, ...
    'stim', {{
    setParams(stims.MovingBar,...
    'pre_blank', 0, ...   (s) blank period preceding trials
    'luminance', 30, ...    cd/m^2 mid-value luminance"
    'contrast', 0.99, ...  Michelson contrast
    'bg_color', 10, ...   0-254
    'bar_color', 254, ... 0-254
    'direction', 90, ... (degrees) 0=north, 90=east
    'bar_length', 1, ... in units of half-diagonal
    'bar_width', 0.03, ... in units of half-diagonal
    'bar_offset', 0, ... offset to the right (when facing in direction of motion) in units of half-diagonal
    'start_pos', -1, ... the starting position of the bar moviement. 1 is the distance from the center to corner"
    'end_pos', 1, ... (-1 1) the ending position of the bar movement
    'trial_duration', 10) ... (s) movement duration
    }});


simpleGrating = struct(...
    'prompt', 'grating: 1s ON/1s OFF (384 s)', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Grating), ...
    'constants', ...
    struct(...
    'stimulus', 'grating', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 36, ...
    'stim', {{
    setParams(stims.Grating, ...
    'grating','sqr', ...
    'direction', 0:30:359, ...
    'pre_blank', 0.5, ...
    'trial_duration', 0.5, ...
    'aperture_radius', 2.0, ...
    'second_photodiode', [-1,1], ...
    'second_photodiode_time', 0.1, ...
    'init_phase', 0) ...
    }});

oddballOriGrating = struct(...
    'prompt', 'grating: 1s ON/1s OFF (384 s)', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Grating), ...
    'constants', ...
    struct(...
    'stimulus', 'grating', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 4, ...
    'stim', {{
    setParams(stims.Grating, ...
    'grating','sqr', ...
    'luminance', 5, ...
    'contrast', [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], ...%'direction', [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], ...
    'direction', 0, ...
    'pre_blank', 1, ...
    'trial_duration', 1, ...
    'aperture_radius', 2.0, ...
    'second_photodiode', 1, ...
    'second_photodiode_time', 0.1, ...
    'temp_freq', 1,...
    'spatial_freq', 0.02, ...
    'init_phase', 0) ...
    
    setParams(stims.Grating, ...
    'grating','sqr', ...
    'direction', 180, ... %'direction', [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 90], ...
    'pre_blank', 1, ...
    'trial_duration', 1, ...
    'aperture_radius', 2.0, ...
    'second_photodiode', 1, ...
    'second_photodiode_time', 0.1, ...
    'temp_freq', 8,...
    'spatial_freq', 0.02, ...
    'init_phase', 0) ...
    }});

photoStimOnly = struct(...
    'prompt', 'LED stim protocol for CalTech probe', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Grating), ...
    'constants', ...
    struct(...
    'stimulus', 'grating', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 100, ...
    'stim', {{
    setParams(stims.Grating, ...
    'contrast', 0, ...
    'grating','sqr', ...
    'direction', 0, ...
    'pre_blank', 2, ...
    'trial_duration', 1, ...
    'aperture_radius', 2.0, ...
    'second_photodiode', 1, ...
    'second_photodiode_time', .1, ...
    'init_phase', 0) ...
    }});



jakeGrating = struct(...
    'prompt', 'JakeGrating: 0.5s ON/1s OFF (540s)', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Grating), ...
    'constants', ...
    struct(...
    'stimulus', 'grating', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 15, ... % 100 for imaging @38000 frames
    'stim', {{
    setParams(stims.Grating, ...
    'grating','sqr', ...
    'direction', 0:22.5:359, ... % 0:45:359 for imaging @38000 frames
    'pre_blank', 0.5 , ...
    'trial_duration', 0.5, ...
    'second_photodiode',[-1,1], ...
    'aperture_radius', 2.0, ...
    'init_phase', [0]) ...
    }});

gammaGrating = struct(...
    'prompt', 'gammaGrating for luminance measurements', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Grating), ...
    'constants', ...
    struct(...
    'stimulus', 'grating', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 1, ...
    'stim', {{
    setParams(stims.Grating, ...
    'grating','sqr', ...
    'direction', 0:45:359, ...
    'pre_blank', 5 , ...
    'trial_duration', 5, ...
    'second_photodiode',[-1], ...
    'aperture_radius', 2.0, ...
    'temp_freq', 2,...
    'spatial_freq', 0.04, ...
    'init_phase', [0]) ...
    }});

groupedGrating = struct(...
    'prompt', 'Jake''s grouped stim ', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Grating), ...
    'constants', struct(...
    'stimulus', 'grating', ... % stimulus name recorded in the session table
    'monitor_distance', 10, ...  (cm)
    'monitor_size', 7, ...       (inches) diagonal
    'monitor_aspect', 1.7, ...   (physical aspect ratio W/H)
    'resolution_x', 1024, ...     (pixels)
    'resolution_y',  600 ...      (pixels)
    ), ...
    'blocks', 20, ...
    'stim', {{
    
    setParams(stims.Grating, ...
    'second_photodiode', [-1 1], ...
    'direction', 0:15:359, ...
    'pre_blank', 0.1, ...
    'trial_duration', 0.2, ...
    'temp_freq', 2,...
    'spatial_freq', 0.04, ...
    'aperture_radius', 2.0)
    
    stims.Pause(10)
    
    %     setParams(stims.Grating, ...
    %     'second_photodiode',  [-1 1], ...
    %     'direction', 0:30:359,  ...
    %     'pre_blank', 0, ...
    %     'trial_duration', 0.1, ...
    %     'temp_freq', 2,...
    %     'spatial_freq', 0.04, ...
    %     'aperture_radius', 2.0)
    %
    %     stims.Pause(20)
    }}...
    );


quadrantGrating = struct(...
    'prompt', 'Shan''s quadrant grating (960 s)', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Grating), ...
    'constants', struct(...
    'stimulus', 'grating', ... % stimulus name recorded in the session table
    'monitor_distance', 10, ...  (cm)
    'monitor_size', 7, ...       (inches) diagonal
    'monitor_aspect', 1.7, ...   (physical aspect ratio W/H)
    'resolution_x', 1024, ...     (pixels)
    'resolution_y',  600 ...      (pixels)
    ), ...
    'blocks', 8, ...
    'stim', {{
    
    
    setParams(stims.Grating, ...
    'pre_blank', 3, ...
    'trial_duration', 2, ...
    'direction', [90, 180], ...
    'aperture_radius', 0.15, ...
    'aperture_x', [-0.4,0.2], ...
    'aperture_y', [-0.36,0.32], ...
    'temp_freq', 4,...
    'spatial_freq',0.08)...
    
    %     setParams(stims.Grating, ...
    %     'pre_blank', 5, ...
    %     'trial_duration', 2, ...
    %     'direction', 90, ...
    %     'aperture_radius', 0.2, ...
    %     'aperture_x', -0.47, ...
    %     'aperture_y', 0.32, ...
    %     'temp_freq', 4,...
    %     'spatial_freq',0.03)...
    
    %     setParams(stims.Grating, ...
    %     'pre_blank', 5, ...
    %     'trial_duration', 2, ...
    %     'direction', 90, ...
    %     'aperture_radius', 0.2, ...
    %     'aperture_x', 0.1, ...
    %     'aperture_y', -0.32, ...
    %     'temp_freq', 4,...
    %     'spatial_freq',0.03)...
    %
    %     setParams(stims.Grating, ...
    %     'pre_blank', 5, ...
    %     'trial_duration', 2, ...
    %     'direction', 90, ...
    %     'aperture_radius', 0.2, ...
    %     'aperture_x', 0.1, ...
    %     'aperture_y', 0.32, ...
    %     'temp_freq', 4,...
    %     'spatial_freq',0.03)...
    %
    %     setParams(stims.Grating, ...
    %     'pre_blank', 5, ...
    %     'trial_duration', 2, ...
    %     'direction', 180, ...
    %     'aperture_radius', 0.2, ...
    %     'aperture_x', -0.47, ...
    %     'aperture_y', -0.32, ...
    %     'temp_freq', 4,...
    %     'spatial_freq',0.03)...
    %
    %     setParams(stims.Grating, ...
    %     'pre_blank', 5, ...
    %     'trial_duration', 2, ...
    %     'direction', 180, ...
    %     'aperture_radius', 0.2, ...
    %     'aperture_x', -0.47, ...
    %     'aperture_y', 0.32, ...
    %     'temp_freq', 4,...
    %     'spatial_freq',0.03)...
    %
    %     setParams(stims.Grating, ...
    %     'pre_blank', 5, ...
    %     'trial_duration', 2, ...
    %     'direction', 180, ...
    %     'aperture_radius', 0.2, ...
    %     'aperture_x', 0.1, ...
    %     'aperture_y', -0.32, ...
    %     'temp_freq', 4,...
    %     'spatial_freq',0.03)...
    %
    %     setParams(stims.Grating, ...
    %     'pre_blank', 5, ...
    %     'trial_duration', 2, ...
    %     'direction', 180, ...
    %     'aperture_radius', 0.2, ...
    %     'aperture_x', 0.1, ...
    %     'aperture_y', 0.32, ...
    %     'temp_freq', 4,...
    %     'spatial_freq',0.03)...
    
    }}...
    );

naturalMovie = struct(...
    'prompt', 'natualMovie: 10s ON/1s OFF (540s)', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.NaturalMovie), ...
    'constants', ...
    struct(...
    'stimulus', 'naturalmovie', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 25, ... % 100 for imaging @38000 frames
    'stim', {{
    setParams(stims.NaturalMovie, ...
    'pre_blank', 1 , ...
    'duration', 10, ...
    'type', {'nat','phs'}) ...
    }});

shanGrating = struct(...
    'prompt', 'ShanGrating: 0.25s ON (300s)', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Grating), ...
    'constants', ...
    struct(...
    'stimulus', 'grating', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 75, ... % 100 for imaging @38000 frames
    'stim', {{
    setParams(stims.Grating, ...
    'grating','sqr', ...
    'direction', 0:22.5:359, ... % 0:45:359 for imaging @38000 frames
    'pre_blank', 0 , ...
    'trial_duration', 0.25, ...
    'second_photodiode',[-1], ...
    'aperture_radius', 2.0, ...
    'temp_freq', 4,...
    'spatial_freq',0.04,...
    'init_phase', [0]) ...
    }});

stGrating = struct(...
    'prompt', 'Spatial and Temportal Grating: 0.25 ON ()', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Grating), ...
    'constants', ...
    struct(...
    'stimulus', 'grating', ...  % stimulus name recorded in the session table
    'monitor_distance', 7, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 10, ... % 100 for imaging @38000 frames
    'stim', {{
    setParams(stims.Grating, ...
    'grating','sqr', ...
    'direction', 0:22.5:359, ... % 0:45:359 for imaging @38000 frames
    'pre_blank', 0.5 , ... %0
    'trial_duration', 0.5, ... %0.1
    'second_photodiode',[-1], ...
    'aperture_radius', 2.0, ...
    'temp_freq', [1 3 6],... % 1,2,4,8,16
    'spatial_freq',[0.02,.04,0.08],... % [.02 .04 .08 .016,0.32
    'init_phase', 0) ... %[0 .33 .66]
    }});

noiseMap = struct(...
    'prompt', 'noiseMap', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.NoiseMap), ...
    'constants', ...
    struct(...
    'stimulus', 'noisemap', ...  % stimulus name recorded in the session table
    'monitor_distance', 7, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 1, ... % 100 for imaging @38000 frames
    'stim', {{
    setParams(stims.NoiseMap, ...
    'rng_seed',    1:25,         ... RNG seed 1:150
    'luminance',   10,           ... cd/m^2
    'contrast',    0.95,        ... Michelson's 0-1
    'tex_ydim',    76,          ... (pixels) texture dimension
    'tex_xdim',    128,          ... (pixels) texture dimension
    'spatial_freq_half', 0.04,  ... (cy/deg) spatial frequency modulated to 50
    'spatial_freq_stop',0.16,    ... (cy/deg), spatial lowpass cutoff
    'temp_bandwidth',4,        ... (Hz) temporal bandwidth
    'contrast_mod_freq', 1/500, ... (Hz) raised cosine contrast modulation
    'contrast_slope', 5,        ... onset slope
    'modulation_shift', 0.2,      ... shift of the signamoid argument (cosine value)
    'frame_downsample', 1,      ... 1=60 fps, 2=30 fps, 3=20 fps, 4=15 fps, etc
    'duration', 45              ... (s) trial duration
    )              ... (s) trial duration
    }});


movingNoise = struct(...
    'prompt', 'movingNoise', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.MovingNoise), ...
    'constants', ...
    struct(...
    'stimulus', 'movingNoise', ...  % stimulus name recorded in the session table
    'monitor_distance', 7, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 1, ... % 100 for imaging @38000 frames
    'stim', {{
    setParams(stims.MovingNoise, ...
    'rng_seed',    1:60,         ... RNG seed 1:60
    'luminance',   10,           ... cd/m^2
    'contrast',    0.95,        ... Michelson's 0-1
    'tex_ydim',    76,          ... (pixels) texture dimension
    'tex_xdim',    128,          ... (pixels) texture dimension
    'spatial_freq_half', 0.04,  ... (cy/deg) spatial frequency modulated to 50 - deprecated in version 3
    'spatial_freq_stop',0.2,    ... (cy/deg), spatial lowpass cutoff
    'temp_bandwidth',4,        ... (Hz) temporal bandwidth
    'frame_downsample', 1,      ... 1=60 fps, 2=30 fps, 3=20 fps, 4=15 fps, etc
    'n_dirs', 16, ...  number of directions of motion
    'ori_bands', 2, ...  orientation width expressed in units of 2*pi/n_dirs.  Must be integer
    'ori_modulation', 1.0, ...  mix-in proportion of oriented noise
    'ori_on_secs', 0.875, ...  seconds of movement and orientation bias
    'ori_off_secs', 1, ...  second with no movement or orientation bias
    'speed', 25 ...  degrees per second
    )
    }});

vanGogh = struct(...
    'prompt', 'Van Gogh', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.VanGogh), ...
    'constants', ...
    struct(...
    'stimulus', 'vangogh', ...  % stimulus name recorded in the session table
    'monitor_distance', 7, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 1, ...
    'stim', {{
    setParams(stims.VanGogh, ...
    'rng_seed',    1:60,         ... RNG seed 1:150
    'frame_downsample', 1,      ... 1=60 fps, 2=30 fps, 3=20 fps, 4=15 fps, etc
    'luminance',   10,           ... cd/m^2
    'contrast',    0.95,        ... Michelson's 0-1
    'duration', 30,            ... (seconds)
    'tex_ydim', 76,           ... (pixels) texture dimension
    'tex_xdim', 128,           ... (pixels) texture dimension
    'spatial_freq_half', 0.04, ... (cy/deg) spatial frequency modulated to 50 - deprecated in version 3
    'spatial_freq_stop', 0.3,  ... (cy/deg), spatial lowpass cutoff
    'temp_bandwidth', 4,       ... (Hz) temporal bandwidth
    'ori_bandwidth', pi / 20,  ... (rad) bandwidth of orientation filter
    'ori_map_spatial_bandwidth', 0.05,  ... (cy/deg) spatial bandwidth for ori map
    'ori_map_temp_bandwidth', 1,        ... (Hz) temporal bandwidth for ori map
    'contrast_spatial_bandwidth', 0.03, ... (cy/deg) spatial bandwidth of contrast map
    'contrast_temp_bandwidth', 1,       ... (Hz) temporal bandwidth of contrast map
    'contrast_exponent', 1/3            ... exponent of power function for contrast map
    )
    }});


fastMovingBar = struct(...
    'prompt', 'moving bar: 0.3 Hz (72 s total)', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.MovingBar), ...
    'constants', ...
    struct(...
    'stimulus', 'moving bar', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 3, ...
    'stim', {{
    setParams(stims.MovingBar,...
    'pre_blank', 0, ...   (s) blank period preceding trials
    'luminance', 30, ...    cd/m^2 mid-value luminance"
    'contrast', 0.99, ...  Michelson contrast
    'bg_color', 128, ...   0-254
    'bar_color', [1 254], ... 0-254
    'direction', [0 90 180 270], ... (degrees) 0=north, 90=east
    'bar_length', 1, ... in units of half-diagonal
    'bar_width', 0.03, ... in units of half-diagonal
    'bar_offset', 0, ... offset to the right (when facing in direction of motion) in units of half-diagonal
    'start_pos', -1, ... the starting position of the bar moviement. 1 is the distance from the center to corner"
    'end_pos', 1, ... (-1 1) the ending position of the bar movement
    'trial_duration', 3) ... (s) movement duration
    }});



trippy = struct(...
    'prompt', 'trippy (30 mins total)', ...
    'logger', stims.core.Logger(psy.Session, psy.Condition, psy.Trial, psy.Trippy), ...
    'constants', ...
    struct(...
    'stimulus', 'trippy', ...  % stimulus name recorded in the session table
    'monitor_distance', 10, ... (cm)
    'monitor_size', 7, ...      (inches) diagonal
    'monitor_aspect', 1.7, ...  (physical aspect ratio W/H)
    'resolution_x', 1024, ...   (pixels)
    'resolution_y',  600 ...    (pixels)
    ), ...
    'blocks', 30, ...
    'stim', {{
    setParams(stims.Trippy,...
    'pre_blank', 0, ...   (s) blank period preceding trials
    'luminance', 30, ...    cd/m^2 mid-value luminance"
    'contrast', 0.99, ...  Michelson contrast
    'rng_seed', 1:30, ... RNG seed
    'duration', 60, ... (s) trial duration
    'tex_ydim', 150, ...  (pixels) texture dimension
    'tex_xdim', 256, ...  (pixels) texture dimension
    'temp_bandwidth', 4, ... (Hz) temporal bandwidth of phase 
    'max_spatial_freq', 0.2, ... (cy)/degree
    'control_points', 8, ...  number of control points along each dimension
    'frame_downsample', 1)
    }});


% menu items callback
% menu = [
%     simpleGrating
%     groupedGrating
%     quadrantGrating
%     jakeGrating
%     movingBar
%     photoStimOnly
%     shanGrating
%     stGrating
%     oddballOriGrating
%     ];

result = [
%     simpleGrating
%     shanGrating
%     quadrantGrating
%     movingBar
%     movingNoise
%     vanGogh
%     fastMovingBar
    trippy
    ];
